In [ ]:
import networkx as nx
import numpy as np
#import import_ipynb

In [ ]:
!pip install ndlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ndlib
  Downloading ndlib-5.1.1-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.2/110.2 KB 11.7 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from ndlib) (1.21.6)
Requirement already satisfied: networkx in /usr/local/lib/python3.8/dist-packages (from ndlib) (3.0)
Collecting netdispatch
  Downloading netdispatch-0.1.0-py3-none-any.whl (3.3 kB)
Collecting python-igraph
  Downloading python-igraph-0.10.3.tar.gz (9.5 kB)
  Preparing metadata (setup.py) ... done
Collecting dynetx
  Downloading dynetx-0.3.1-py3-none-any.whl (39 kB)
Requirement already satisfied: future in /usr/local/lib/python3.8/dist-packages (from ndlib) (0.16.0)
Requirement already satisfied: bokeh in /usr/local/lib/python3.8/dist-packages (from ndlib) (2.3.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from ndlib) (1.7.3)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (2.8.2)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (6.0.4)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (6.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (7.1.2)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (4.4.0)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (2.11.3)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.8/dist-packages (from bokeh->ndlib) (21.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from dynetx->ndlib) (4.4.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from dynetx->ndlib) (4.64.1)
Collecting igraph==0.10.3
  Downloading igraph-0.10.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 106.6 MB/s eta 0:00:00
Collecting texttable>=1.6.2
  Downloading texttable-1.6.7-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=2.9->bokeh->ndlib) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=16.8->bokeh->ndlib) (3.0.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.1->bokeh->ndlib) (1.15.0)
Building wheels for collected packages: python-igraph
  Building wheel for python-igraph (setup.py) ... done
  Created wheel for python-igraph: filename=python_igraph-0.10.3-py3-none-any.whl size=9074 sha256=9a358a20aa6aca103951a9887ad9c6f9f9f4fffb3ade45246e3f7e1a53aba368
  Stored in directory: /root/.cache/pip/wheels/89/e5/ce/6b6a72dd08502dee685b95fb8733a983bc86575c013371f15a
Successfully built python-igraph
Installing collected packages: texttable, igraph, dynetx, python-igraph, netdispatch, ndlib
Successfully installed dynetx-0.3.1 igraph-0.10.3 ndlib-5.1.1 netdispatch-0.1.0 python-igraph-0.10.3 texttable-1.6.7

In [ ]:
import fcts

In [ ]:
g = nx.read_edgelist('fbData.txt',create_using=nx.Graph(),nodetype=int)

In [ ]:
#centrality measuers computing 
dc = nx.degree_centrality(g)    
bc = nx.betweenness_centrality(g)
cc = nx.closeness_centrality(g)
ec = nx.eigenvector_centrality(g)

In [ ]:
evolution_matrix = fcts.creat_evaluation_matrix(g,dc,bc,cc,ec)#evolution matrix is evaluation matrix only as a dataFrame 
ev_matrix_np = fcts.evolution_matrix_tonp(evolution_matrix)#numpy array version of evaluation matrix
weights = fcts.entropy(g=g,ev_mat=ev_matrix_np)
t = fcts.Topsis(ev_matrix_np,weights,criteria = np.array([True,True,True,True]))
t.calc()
top_k_noeuds, tous_les_noeuds = fcts.top_meth(evolution_matrix,t=t)

Step 1
 [[8.59336305e-02 1.46305921e-01 3.53342667e-01 3.39179617e-05]
 [4.21000495e-03 2.78327442e-06 2.61376141e-01 6.04534613e-07]
 [2.47647350e-03 7.59502118e-08 2.61257764e-01 2.23346094e-07]
 ...
 [4.95294700e-04 0.00000000e+00 1.83988700e-01 2.93122343e-10]
 [9.90589401e-04 7.15684688e-08 1.84005468e-01 2.98923251e-10]
 [2.22882615e-03 6.33892152e-07 1.84047402e-01 8.91517473e-10]]

Step 2
 [[8.00164615e-02 1.97368601e-01 1.99619580e-02 3.39179617e-05]
 [3.92011483e-03 3.75467359e-06 1.47663445e-02 6.04534613e-07]
 [2.30594990e-03 1.02457829e-07 1.47596568e-02 2.23346094e-07]
 ...
 [4.61189980e-04 0.00000000e+00 1.03943708e-02 2.93122343e-10]
 [9.22379960e-04 9.65468003e-08 1.03953181e-02 2.98923251e-10]
 [2.07535491e-03 8.55128803e-07 1.03976871e-02 8.91517473e-10]]

Step 3
 [[5.05637918e-03 1.20731938e-01 2.19598490e-05 1.09894281e-05]
 [2.47718865e-04 2.29676360e-06 1.62442330e-05 1.95869366e-07]
 [1.45716979e-04 6.26742662e-08 1.62368760e-05 7.23641902e-08]
 ...
 [2.91433958e-05 0.00000000e+00 1.14346906e-05 9.49717124e-11]
 [5.82867917e-05 5.90584432e-08 1.14357327e-05 9.68512082e-11]
 [1.31145281e-04 5.23089068e-07 1.14383389e-05 2.88851884e-10]]

Step 4
 [1.45716979e-05 0.00000000e+00 1.10783188e-05 2.06882757e-14] [1.52274243e-02 3.96524477e-01 2.85698036e-05 3.09118794e-02]

Step 5
 [1.20837167e-01 2.33215783e-04 1.31246732e-04 ... 1.45760551e-05
 4.37165947e-05 1.16575313e-04] [0.27770459 0.39800724 0.39801333 ... 0.39801783 0.39801666 0.39801343]

Step 6
 [3.03198259e-01 5.85615499e-04 3.29645914e-04 ... 3.66202722e-05
 1.09824030e-04 2.92807154e-04] [0.69680174 0.99941438 0.99967035 ... 0.99996338 0.99989018 0.99970719]

entrer le nomber des noeuds influents voulu: 10

In [ ]:
import pandas as pd
kinit = pd.read_csv('kinit.csv')
kinit = kinit.drop(columns = ['Unnamed: 0'], axis=1)

kinit

      node        dc        bc        cc            ec             C
0      107  0.258791  0.480518  0.459699  2.606940e-04  9.279133e-01
1     1684  0.196137  0.337797  0.393606  7.164260e-06  6.960689e-01
2     3437  0.135463  0.236115  0.314413  9.531613e-08  4.885255e-01
3     1912  0.186974  0.229295  0.350947  9.540696e-02  4.808275e-01
4     1085  0.016345  0.149015  0.357852  3.164082e-06  3.084781e-01
...    ...       ...       ...       ...           ...           ...
4034  4035  0.000248  0.000000  0.183980  2.912901e-10  8.940556e-07
4035  4010  0.000248  0.000000  0.183980  2.912901e-10  8.940556e-07
4036  4015  0.000248  0.000000  0.183980  2.912901e-10  8.940556e-07
4037   692  0.000248  0.000000  0.178255  6.385265e-14  0.000000e+00
4038   801  0.000248  0.000000  0.178255  6.385265e-14  0.000000e+00

[4039 rows x 6 columns]

In [ ]:
#score = 0.3dc + 0.2bc + 0.2cc + 0.3ec
score = []
for idx, row in kinit.iterrows():
  score_value = 0.33*row['dc'] + 0.33*row['bc'] + 0.34*row['cc']
  score.append(score_value)

kinit['score'] = score

In [ ]:
kinit

      node        dc        bc        cc            ec         C     score
0      107  0.258791  0.480518  0.459699  2.606940e-04  0.927913  0.400270
1     1684  0.196137  0.337797  0.393606  7.164260e-06  0.696069  0.310024
3     1912  0.186974  0.229295  0.350947  9.540696e-02  0.480827  0.256691
2     3437  0.135463  0.236115  0.314413  9.531613e-08  0.488526  0.229521
5        0  0.085934  0.146306  0.353343  3.391796e-05  0.303198  0.196776
...    ...       ...       ...       ...           ...       ...       ...
3966   841  0.000495  0.000000  0.178262  6.446055e-14  0.000037  0.060773
3968   749  0.000495  0.000000  0.178262  6.433195e-14  0.000037  0.060773
3970   775  0.000495  0.000000  0.178262  6.433195e-14  0.000037  0.060773
4037   692  0.000248  0.000000  0.178255  6.385265e-14  0.000000  0.060688
4038   801  0.000248  0.000000  0.178255  6.385265e-14  0.000000  0.060688

[4039 rows x 7 columns]

In [ ]:
kinit = kinit.sort_values(by='score',ascending=False)
kinit

      node        dc        bc        cc            ec         C     score
0      107  0.258791  0.480518  0.459699  2.606940e-04  0.927913  0.400270
1     1684  0.196137  0.337797  0.393606  7.164260e-06  0.696069  0.310024
3     1912  0.186974  0.229295  0.350947  9.540696e-02  0.480827  0.256691
2     3437  0.135463  0.236115  0.314413  9.531613e-08  0.488526  0.229521
5        0  0.085934  0.146306  0.353343  3.391796e-05  0.303198  0.196776
...    ...       ...       ...       ...           ...       ...       ...
3967   699  0.000495  0.000000  0.178262  6.477108e-14  0.000037  0.060773
3968   749  0.000495  0.000000  0.178262  6.433195e-14  0.000037  0.060773
3969   750  0.000495  0.000000  0.178262  6.638013e-14  0.000037  0.060773
4037   692  0.000248  0.000000  0.178255  6.385265e-14  0.000000  0.060688
4038   801  0.000248  0.000000  0.178255  6.385265e-14  0.000000  0.060688

[4039 rows x 7 columns]

In [ ]:
import math 

def notre_kmeans(dataframe, k = 10):


    data = dataframe.values
    n = data.shape[0]
    # select the top k points (highest scores) as centroids
    centroids = data[:k]
    labels = np.zeros(n)

    # Assign each data point to the closest cluster center
    #new_labels = np.array([np.argmin([np.abs(data[i]-cent) for cent in centroids]) for i in range(n)])
    while True: 

        new_labels = np.array([np.argmin([np.sqrt(np.sum((data[i]-cent)**2)) for cent in centroids]) for i in range(n)])
        labels = new_labels
        if (new_labels == labels).all():
            break
        labels = new_labels
        # Update cluster centers
        for i in range(k):
            centroids[i] = np.mean(data[labels == i], axis = 0)


    return labels, centroids
    



lbs, cents = notre_kmeans(kinit[['score', 'C']],10)
cents

it

array([[0.40026997, 0.92791331],
       [0.31002418, 0.69606894],
       [0.25669089, 0.48082748],
       [0.22952115, 0.48852551],
       [0.19677556, 0.30319826],
       [0.17623836, 0.30847809],
       [0.16486485, 0.13333984],
       [0.16393617, 0.17477504],
       [0.16208467, 0.13014843],
       [0.15702543, 0.07918571]])

On a essayé differents poids mais les résultats n'ont pas changés, le clustring  en se basant sur le score a echoué

In [ ]:
len([lbl for lbl in lbs if lbl == 9])

4027